Card Controller de Users y CRUD
wolox-training/js-java pull request #6
Opened 2020-04-30 20:54 UTC by jstegman-3355

Card Controller de Users y CRUD

2020-04-30 22:22 UTC, leandrocostawolox requested changes
Genial! Sólo un comentario acerca del nombre de los métodos :)

2020-04-30 22:22 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +	public User agregarLibro(@PathVariable(required = true) Long userid, @PathVariable(required = true) Long bookid) {
Los nombres de los métodos por convención van en inglés

2020-04-30 22:22 UTC, leandrocostawolox commented on src/main/java/wolox/training/controllers/UserController.java
> +	public User borrarLibro(@PathVariable(required = true) Long userid, @PathVariable(required = true) Long bookid) {
Los nombres de los métodos por convención van en inglés

2020-05-03 19:40 UTC, jstegman-3355 commented on src/main/java/wolox/training/controllers/UserController.java
> +	public User agregarLibro(@PathVariable(required = true) Long userid, @PathVariable(required = true) Long bookid) {
corregido

2020-05-03 19:40 UTC, jstegman-3355 commented on src/main/java/wolox/training/controllers/UserController.java
> +	public User borrarLibro(@PathVariable(required = true) Long userid, @PathVariable(required = true) Long bookid) {
corregido

2020-05-04 13:40 UTC, leandrocostawolox approved these changes
Listo, Jony! Podés mergearlo :)

2020-05-04 14:19 UTC, merged