Agrega métodos más complejos a los Repositorios
wolox-training/js-java pull request #9
Opened 2020-05-11 23:29 UTC by jstegman-3355

CARD Agregar métodos más complejos a los Repositorios

2020-05-12 14:06 UTC, leandrocostawolox requested changes
Los queries están bastante bien, Jony! Te dejé unos comentarios para mejorar algunos detalles

2020-05-12 14:06 UTC, leandrocostawolox commented on src/main/java/wolox/training/repositories/UserRepository.java
> +	        @Param("cadena") String cadena);
Tres comentarios en este punto :)
1. Usemos valores en ingles para las variables, en lugar de cadena podría ser "name"
2. El nombre del método habría que cambiarlo para que siga el cambio de variable de "cadena" por "name" también
3. Qué pasa si nos mandan fechas en null en este caso? O nos mandan sólo una? Creo que no contemplamos ese caso. Para chequear si una fecha es null tendríamos que castearla y parte de la condición quedaría así: ...`OR (cast(:startDate as date) IS NULL`

2020-05-12 14:06 UTC, leandrocostawolox commented on src/test/java/wolox/training/repositoryTest/UserRepositoryTest.java
> +	public void givenUsers_WhenSearchByBirthDateBetweenAndCadena_ThenFind1Users() {
Faltaría el test del caso de uso en el que se manda alguna fecha en NULL, ahí saltaría el problema que comenté antes :)

2020-05-12 14:06 UTC, leandrocostawolox commented on src/main/java/wolox/training/repositories/BookRepository.java
> +	@Query("select u from Book u where (u.publisher = :publisher or null = :publisher) and (u.genre = :genre or null = :genre) and (u.year = :year or null = :year)")
Esta línea quedó muy larga, tengo que scrollear para llegar a verla. Eso es lo que queremos evitar para que sea más fácilmente legible. En el documento de Configuración del IDE que les pasé se corregía eso si no me equivoco, cualquier cosa avisame y lo vemos!

2020-05-12 20:18 UTC, Gianni-Nicolas requested changes
Genial!! solo faltan unos detalles 😄

2020-05-12 20:18 UTC, GNico95 commented on src/main/java/wolox/training/repositories/UserRepository.java
>  	List<User> findByBirthDateBetweenAndCadena(@Param("dateFrom") LocalDate dateFrom, @Param("dateTo") LocalDate dateTo,
Según lo marcado por Lea falta cambiar la palabra "Cadena" por "Name" en el nombre del método.

2020-05-12 20:18 UTC, GNico95 commented on src/main/java/wolox/training/repositories/UserRepository.java
> +	        + " u.birthDate between :dateFrom and :dateTo) and (:name = null or lower(u.name) like lower(concat('%',:name,'%'))))")
Los = null deberían ir con **"is null"** porque con = null puede haber motores de bases de datos que no lo interpreten y devuelvan resultados inesperados.

2020-05-12 20:18 UTC, GNico95 commented on src/main/java/wolox/training/repositories/BookRepository.java
> +	@Query("select u from Book u where (u.publisher = :publisher or null = :publisher) and (u.genre = :genre or null = :genre) and (u.year = :year or null = :year)")
Los = null deberían ir con **"is null"** porque con = null puede haber motores de bases de datos que no lo interpreten y devuelvan resultados inesperados.

2020-05-12 22:43 UTC, Gianni-Nicolas approved these changes

2020-05-13 03:05 UTC, leandrocostawolox approved these changes

2020-05-13 12:46 UTC, merged